version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.04.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Set permission
          command: chmod +x ./gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew :app:testDebugUnitTest
      - run:
          name: Build APK
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debug-apk
      - store_test_results:
          path: app/build/test-results