version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.04.1  # ✅ Ganti ke image Docker resmi
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Set Gradle permission
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      - run:
          name: Run Unit Tests
          command: ./gradlew test
